repositories:
- name: grafana
  url: https://grafana.github.io/helm-charts

- name: prometheus-grafana
  url: https://prometheus-community.github.io/helm-charts

releases:

- name: grafana
  namespace: lgtm
  createNamespace: true
  chart: grafana/grafana
  values:
  - ./grafana/values-grafana.yaml 


# - name: mimir
#   namespace: lgtm
#   createNamespace: true
#   chart: grafana/mimir-distributed
#   values:
#   - ./mimir/values-mimir.yaml
  # - ./mimir/small.yaml # up to 1m metrics
  # - ./mimir/large.yaml # up to 10m metrics


# - name: prometheus
#   namespace: lgtm
#   createNamespace: true
#   chart: prometheus-community/kube-prometheus-stack
#   values:
#   - ./prometheus/values-prometheus.yaml


- name: tempo
  namespace: lgtm
  createNamespace: true
  chart: grafana/tempo-distributed
  values:
  - ./tempo/values-tempo.yaml
